apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-daisy-cms
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-daisy-cms
  template:
    metadata:
      labels:
        app: blue-daisy-cms
    spec:
      containers:
        - name: blue-daisy-cms
          image: blue-daisy-cms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: blue-daisy-cms-balancer
spec:
  selector:
    app: blue-daisy-cms
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
